-- Create the final table with session numbers

-- check if THREAD_MSG_NUM IS A NUMBER THAT HAS 10 AS THE LAST TWO DIGITS

-- Final logic        
CREATE OR REPLACE TABLE FINAL_MESSAGES AS
SELECT 
    1 + SUM(CASE WHEN MESSAGE = 'Start Init' OR MESSAGE = 'End Init' OR MESSAGE = 'New Scene' 
                 OR MOD(THREAD_MSG_NUM, 1000) = 10 -- NEW LOCATION MARKER
            THEN 1 ELSE 0 END) OVER (ORDER BY MSG_ID ROWS UNBOUNDED PRECEDING) AS SESSION_NUM,
    MSG_ID,
    LOCATION_NAME,
    CHARACTER_NAME,
    MESSAGE    
FROM STG_MESSAGES
ORDER BY MSG_ID
;


SELECT THREAD_ID, COUNT(*) AS MESSAGE_COUNT
FROM STG_MESSAGES
GROUP BY THREAD_ID
ORDER BY THREAD_ID
;


-- show the preceding 3 rows and the following 3 rows for messages with 'Start Init'
WITH CONTEXT AS (
    SELECT 
        THREAD_MSG_NUM,
        LOCATION_NAME,
        CHARACTER_NAME,
        LAG(MESSAGE, 3) OVER (ORDER BY THREAD_MSG_NUM) AS PREVIOUS_3,
        LAG(MESSAGE, 2) OVER (ORDER BY THREAD_MSG_NUM) AS PREVIOUS_2,
        LAG(MESSAGE, 1) OVER (ORDER BY THREAD_MSG_NUM) AS PREVIOUS_1,
        MESSAGE,
        LEAD(MESSAGE, 1) OVER (ORDER BY THREAD_MSG_NUM) AS NEXT_1,
        LEAD(MESSAGE, 2) OVER (ORDER BY THREAD_MSG_NUM) AS NEXT_2,
        LEAD(MESSAGE, 3) OVER (ORDER BY THREAD_MSG_NUM) AS NEXT_3
    FROM STG_MESSAGES
)
SELECT * 
FROM CONTEXT
--WHERE MESSAGE = 'Start Init' OR
WHERE MESSAGE = 'End Init'
ORDER BY THREAD_MSG_NUM
;


SELECT THREAD_MSG_NUM, LOCATION_NAME, MESSAGE
FROM STG_MESSAGES 
WHERE THREAD_MSG_NUM >= 9005985
ORDER BY THREAD_MSG_NUM
limit 200;

8004590 -- NEW SCENE

SELECT MSG_ID, LEFT(MSG_CONTENT, 25) AS MESSAGE_START, *
FROM WPA.RAW_VIEWS.v_thread17_messages 
--WHERE MSG_ID > 1345160368225255505 AND MSG_ID < 1351589087035002950
;



