
USE ROLE SECURITYADMIN;

Use database WPA;
use schema WPA.APPS;

-- Create the WPA_SI_ROLE role
CREATE ROLE IF NOT EXISTS WPA_SI_ROLE;

-- Grant out to the WPA_SI_ROLE role
GRANT DATABASE ROLE SNOWFLAKE.CORTEX_USER TO ROLE WPA_SI_ROLE;  -- Enables access to Cortex AI functionality
GRANT USAGE ON DATABASE SNOWFLAKE_INTELLIGENCE TO ROLE WPA_SI_ROLE ;  -- WPA_SI_ROLE can access the DB
GRANT USAGE ON SCHEMA SNOWFLAKE_INTELLIGENCE.AGENTS TO ROLE WPA_SI_ROLE;  -- WPA_SI_ROLE can access the public schema
GRANT CREATE AGENT ON SCHEMA SNOWFLAKE_INTELLIGENCE.AGENTS TO ROLE WPA_SI_ROLE;  -- Only WPA_SI_ROLE can create agents
GRANT USAGE ON DATABASE WPA TO ROLE WPA_SI_ROLE ;  -- WPA_SI_ROLE can access the DB
GRANT USAGE ON SCHEMA WPA.APPS TO ROLE WPA_SI_ROLE;  -- WPA_SI_ROLE can access the apps schema
GRANT CREATE SEMANTIC VIEW ON SCHEMA WPA.APPS TO ROLE WPA_SI_ROLE; -- grant create semantic views for cortex analyst to WPA_SI_ROLE
GRANT CREATE CORTEX SEARCH SERVICE ON SCHEMA WPA.APPS TO ROLE WPA_SI_ROLE; -- grant create cortex search service to WPA_SI_ROLE
-- Grant out to the WPA_SI_ROLE role
CREATE ROLE IF NOT EXISTS WPA_SI_ROLE ;
GRANT DATABASE ROLE SNOWFLAKE.CORTEX_USER TO ROLE WPA_SI_ROLE;  -- Enables access to Cortex AI functionality
GRANT USAGE ON DATABASE SNOWFLAKE_INTELLIGENCE TO ROLE WPA_SI_ROLE ;  -- WPA_SI_ROLE can access the DB
GRANT USAGE ON SCHEMA SNOWFLAKE_INTELLIGENCE.AGENTS TO ROLE WPA_SI_ROLE;  -- WPA_SI_ROLE can access the public schema
GRANT USAGE ON DATABASE WPA TO ROLE WPA_SI_ROLE ;  -- WPA_SI_ROLE can access the DB
GRANT USAGE ON SCHEMA WPA.APPS TO ROLE WPA_SI_ROLE;  -- WPA_SI_ROLE can access the apps schema
GRANT CREATE SEMANTIC VIEW ON SCHEMA WPA.APPS TO ROLE WPA_SI_ROLE; -- grant create semantic views for cortex analyst to WPA_SI_ROLE
GRANT CREATE CORTEX SEARCH SERVICE ON SCHEMA WPA.APPS TO ROLE WPA_SI_ROLE; -- grant create cortex search service to WPA_SI_ROLE
GRANT CREATE AGENT ON SCHEMA WPA.APPS TO ROLE WPA_SI_ROLE;  -- Only WPA_SI_ROLE can create agents

-- Grant out usage and select to tables in WPA.DATA schema
GRANT USAGE ON SCHEMA WPA.DATA TO ROLE WPA_SI_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA WPA.DATA TO ROLE WPA_SI_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA WPA.DATA TO ROLE WPA_SI_ROLE;

-- Grant out usage to COMPUTE_XS warehouse to WPA_SI_ROLE
GRANT USAGE ON WAREHOUSE COMPUTE_XS TO ROLE WPA_SI_ROLE;
GRANT OPERATE ON WAREHOUSE COMPUTE_XS TO ROLE WPA_SI_ROLE;
-- Grant out to the WPA_SI_ROLE user
GRANT ROLE WPA_SI_ROLE TO USER WPA;

-- ====================================================================
-- CREATE NETWORK RULE FOR EXTERNAL ACCESS
-- ====================================================================

USE ROLE ACCOUNTADMIN;
USE DATABASE WPA;
USE SCHEMA WPA.APPS;

-- This allows EGRESS access to all hosts on ports 80 and 443
CREATE OR REPLACE NETWORK RULE SI_WEBACCESSRULE
  TYPE = HOST_PORT
  MODE = EGRESS
  VALUE_LIST = ('0.0.0.0:443', '0.0.0.0:80')
  COMMENT = 'Allow web access for SI';

-- Grant usage on the network rule to WPA_SI_ROLE
GRANT USAGE ON NETWORK RULE WPA.APPS.SI_WEBACCESSRULE TO ROLE WPA_SI_ROLE;

-- Create external access integration using the network rule
CREATE OR REPLACE EXTERNAL ACCESS INTEGRATION SI_WEB_ACCESS_INTEGRATION
  ALLOWED_NETWORK_RULES = (WPA.APPS.SI_WEBACCESSRULE)
  ENABLED = TRUE
  COMMENT = 'External access integration for SI';

-- Grant usage on the external access integration to WPA_SI_ROLE
GRANT USAGE ON INTEGRATION SI_WEB_ACCESS_INTEGRATION TO ROLE WPA_SI_ROLE;
SHOW NETWORK RULES LIKE 'SI_WEBACCESSRULE';
SHOW EXTERNAL ACCESS INTEGRATIONS LIKE 'SI_WEB_ACCESS_INTEGRATION';

-- ====================================================================
-- CREATE NETWORK POLICY FOR INCOMING CONNECTIONS
-- ====================================================================

-- Create network policy to allow incoming connections from specific IP
CREATE OR REPLACE NETWORK POLICY WPA_SI_NETWORK_POLICY
  ALLOWED_IP_LIST = ('0.0.0.0/0')
  COMMENT = 'Allow incoming connections for WPA_SI_ROLE';

-- Apply the network policy to the WPA_SI_ROLE.  Will need to do this prior to using externally (removed every 4 hours)
USE ROLE ACCOUNTADMIN;
ALTER USER WPA SET NETWORK_POLICY = WPA_SI_NETWORK_POLICY;

SHOW NETWORK POLICIES LIKE 'WPA_SI_NETWORK_POLICY';

desc user wpa;
