USE ROLE SYSADMIN;
USE SCHEMA WPA.DATA;

-- rank all the session_nums in a sub-query and then update the session_nums with the corresponding rank
UPDATE FINAL_MESSAGES
SET SESSION_NUM = R.CALCULATED_RANK
FROM (
    SELECT SESSION_NUM , RANK() OVER (ORDER BY SESSION_NUM) AS CALCULATED_RANK
    FROM (
        SELECT DISTINCT SESSION_NUM
        FROM FINAL_MESSAGES
    ) AS S
) AS R
WHERE FINAL_MESSAGES.SESSION_NUM = R.SESSION_NUM
;

SELECT DISTINCT SESSION_NUM, COUNT(*) AS MESSAGE_COUNT
FROM FINAL_MESSAGES
GROUP BY SESSION_NUM
ORDER BY SESSION_NUM
;